export const dataDestinations = [
  {
    id: 1,
    imageUrl: '/images/tanjung-benoa.png',
    title: 'Tanjung Benoa, Bali',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 2000000,
    rating: 4.5,
    day: 3,
    night: 1,
    category: 'sea',
    isPopular: true,
  },
  {
    id: 2,
    imageUrl: '/images/tanjung-tinggi.png',
    title: 'Tanjung Tinggi, Belitung',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 2000000,
    rating: 4.4,
    day: 3,
    night: 2,
    category: 'sea',
    isPopular: true,
  },
  {
    id: 3,
    imageUrl: '/images/gili-meno.png',
    title: 'Gili Meno, Lombok',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 5000000,
    rating: 4.3,
    day: 5,
    night: 2,
    category: 'sea',
    isPopular: false,
  },
  {
    id: 4,
    imageUrl: '/images/pantai-pandawa.png',
    title: 'Pantai Pandawa, Bali',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 5000000,
    rating: 4.2,
    day: 3,
    night: 1,
    category: 'sea',
    isPopular: false,
  },
  {
    id: 5,
    imageUrl: '/images/pantai-kelingking.png',
    title: 'Pantai Kelingking, Bali',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 4000000,
    rating: 4.1,
    day: 5,
    night: 1,
    category: 'sea',
    isPopular: false,
  },
  {
    id: 6,
    imageUrl: '/images/gn-bromo.png',
    title: 'Gunung Bromo, Jawa Timur',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 2500000,
    rating: 4.8,
    day: 3,
    night: 1,
    category: 'mountain',
    isPopular: true,
  },
  {
    id: 7,
    imageUrl: '/images/gn-semeru.png',
    title: 'Gunung Semeru, Jawa Timur',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 3000000,
    rating: 4.7,
    day: 3,
    night: 1,
    category: 'mountain',
    isPopular: false,
  },
  {
    id: 8,
    imageUrl: '/images/gn-rinjani.png',
    title: 'Gunung Rinjani, Lombok',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 2600000,
    rating: 4.6,
    day: 3,
    night: 1,
    category: 'mountain',
    isPopular: true,
  },
  {
    id: 9,
    imageUrl: '/images/gn-sumbing.png',
    title: 'Gunung Sumbing, Jawa Tengah',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 2500000,
    rating: 4.5,
    day: 3,
    night: 1,
    category: 'mountain',
    isPopular: false,
  },
  {
    id: 10,
    imageUrl: '/images/desa-wae-rebo.png',
    title: 'Desa Wae Rebo, NTT',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 5000000,
    rating: 4.4,
    day: 7,
    night: 2,
    category: 'nature',
    isPopular: false,
  },
  {
    id: 11,
    imageUrl: '/images/bukit-pergasingan.png',
    title: 'Bukit Pergasingan, Lombok',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 5000000,
    rating: 4.3,
    day: 5,
    night: 2,
    category: 'nature',
    isPopular: false,
  },
  {
    id: 12,
    imageUrl: '/images/geopark-ciletuh.png',
    title: 'Geopark Ciletuh, Sukabumi',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 400000,
    rating: 4.2,
    day: 2,
    night: 1,
    category: 'nature',
    isPopular: false,
  },
  {
    id: 13,
    imageUrl: '/images/suspension-brige.png',
    title: 'Suspension Bridge, Sukabumi',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 300000,
    rating: 4.1,
    day: 3,
    night: 1,
    category: 'nature',
    isPopular: false,
  },
  {
    id: 14,
    imageUrl: '/images/curug-ciherang.png',
    title: 'Curug Ciherang, Sukabumi',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 250000,
    rating: 4.8,
    day: 2,
    night: 1,
    category: 'nature',
    isPopular: false,
  },
  {
    id: 15,
    imageUrl: '/images/raja-ampat.png',
    title: 'Raja Ampat, Papua',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 5000000,
    rating: 4.7,
    day: 5,
    night: 2,
    category: 'sea',
    isPolular: true,
  },
  {
    id: 16,
    imageUrl: '/images/danau-toba.png',
    title: 'Danau Toba, Sumatera Utara',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 4000000,
    rating: 4.6,
    day: 3,
    night: 1,
    category: 'nature',
    isPopular: true,
  },
];

export const listBank = [
  {
    name: 'PT. BANK CIMB NIAGA - (CIMB)',
    code: '022',
  },
  {
    name: 'PT. BANK CIMB NIAGA UNIT USAHA SYARIAH - (CIMB SYARIAH)',
    code: '730',
  },
  {
    name: 'PT. BNI SYARIAH',
    code: '427',
  },
  {
    name: 'PT. BANK BCA SYARIAH',
    code: '536',
  },
  {
    name: 'PT. BANK BUKOPIN',
    code: '441',
  },
  {
    name: 'PT. BANK CENTRAL ASIA, TBK - (BCA)',
    code: '014',
  },
  {
    name: 'PT. BANK DANAMON INDONESIA',
    code: '011',
  },
  {
    name: 'PT. BANK DKI',
    code: '111',
  },
  {
    name: 'PT. BANK DBS INDONESIA',
    code: '046',
  },
  {
    name: 'PT. BANK HSBC INDONESIA',
    code: '087',
  },
  {
    name: 'PT. BANK MANDIRI (PERSERO), TBK',
    code: '008',
  },
  {
    name: 'PT. BANK MANDIRI TASPEN POS',
    code: '564',
  },
  {
    name: 'PT. BANK MAYBANK INDONESIA, TBK',
    code: '016',
  },
  {
    name: 'PT. BANK MAYORA',
    code: '553',
  },
  {
    name: 'PT. BANK MEGA, TBK',
    code: '426',
  },
  {
    name: 'PT. BANK MUAMALAT INDONESIA, TBK',
    code: '147',
  },
  {
    name: 'PT. BANK NEGARA INDONESIA (PERSERO), TBK (BNI)',
    code: '009',
  },
  {
    name: 'PT. BANK OCBC NISP, TBK',
    code: '028',
  },
  {
    name: 'PT. BANK OCBC NISP, TBK UNIT USAHA SYARIAH',
    code: '731',
  },
  {
    name: 'PT. BANK PERMATA, TBK',
    code: '013',
  },
  {
    name: 'PT. BANK PERMATA, TBK UNIT USAHA SYARIAH',
    code: '721',
  },
  {
    name: 'PT. BANK RAKYAT INDONESIA (PERSERO), TBK (BRI)',
    code: '002',
  },
  {
    name: 'PT. BANK RAKYAT INDONESIA AGRONIAGA, TBK',
    code: '494',
  },
  {
    name: 'PT. BANK SYARIAH BRI - (BRI SYARIAH)',
    code: '422',
  },
  {
    name: 'PT. BANK SYARIAH BUKOPIN',
    code: '521',
  },
  {
    name: 'PT. BANK SYARIAH MANDIRI',
    code: '451',
  },
  {
    name: 'PT. BANK TABUNGAN NEGARA (PERSERO), TBK (BTN)',
    code: '200',
  },
  {
    name: 'PT. BANK TABUNGAN NEGARA (PERSERO), TBK UNIT USAHA SYARIAH',
    code: '723',
  },
  {
    name: 'PT. BANK TABUNGAN PENSIUNAN NASIONAL - (BTPN)',
    code: '213',
  },
  {
    name: 'PT. BANK TABUNGAN PENSIUNAN NASIONAL SYARIAH - (BTPN Syariah)',
    code: '547',
  },
  {
    name: 'PT. BANK WOORI SAUDARA INDONESIA 1906, TBK (BWS)',
    code: '212',
  },
  {
    name: 'PT. BANK JABAR BANTEN SYARIAH',
    code: '425',
  },
  {
    name: 'PT. BANK PEMBANGUNAN DAERAH BANTEN',
    code: '137',
  },
  {
    name: 'PT. BANK CAPITAL INDONESIA',
    code: '054',
  },
  {
    name: 'PT. BANK DKI UNIT USAHA SYARIAH',
    code: '724',
  },
  {
    name: 'PT. BANK ICBC INDONESIA',
    code: '164',
  },
  {
    name: 'PT. BANK JTRUST INDONESIA, TBK',
    code: '095',
  },
];

export const animals = [
  {
    label: 'Cat',
    value: 'cat',
    description: 'The second most popular pet in the world',
  },
  {
    label: 'Dog',
    value: 'dog',
    description: 'The most popular pet in the world',
  },
  {
    label: 'Elephant',
    value: 'elephant',
    description: 'The largest land animal',
  },
  { label: 'Lion', value: 'lion', description: 'The king of the jungle' },
  { label: 'Tiger', value: 'tiger', description: 'The largest cat species' },
  {
    label: 'Giraffe',
    value: 'giraffe',
    description: 'The tallest land animal',
  },
  {
    label: 'Dolphin',
    value: 'dolphin',
    description: 'A widely distributed and diverse group of aquatic mammals',
  },
  {
    label: 'Penguin',
    value: 'penguin',
    description: 'A group of aquatic flightless birds',
  },
  {
    label: 'Zebra',
    value: 'zebra',
    description: 'A several species of African equids',
  },
  {
    label: 'Shark',
    value: 'shark',
    description:
      'A group of elasmobranch fish characterized by a cartilaginous skeleton',
  },
  {
    label: 'Whale',
    value: 'whale',
    description: 'Diverse group of fully aquatic placental marine mammals',
  },
  {
    label: 'Otter',
    value: 'otter',
    description: 'A carnivorous mammal in the subfamily Lutrinae',
  },
  {
    label: 'Crocodile',
    value: 'crocodile',
    description: 'A large semiaquatic reptile',
  },
];
