export const dataDestinations = [
  {
    id: 1,
    imageUrl: '/images/tanjung-benoa.png',
    title: 'Tanjung Benoa, Bali',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 2000000,
    rating: 4.5,
    day: 3,
    night: 1,
    category: 'sea',
    isPopular: true,
  },
  {
    id: 2,
    imageUrl: '/images/tanjung-tinggi.png',
    title: 'Tanjung Tinggi, Belitung',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 2000000,
    rating: 4.4,
    day: 3,
    night: 2,
    category: 'sea',
    isPopular: true,
  },
  {
    id: 3,
    imageUrl: '/images/gili-meno.png',
    title: 'Gili Meno, Lombok',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 5000000,
    rating: 4.3,
    day: 5,
    night: 2,
    category: 'sea',
    isPopular: false,
  },
  {
    id: 4,
    imageUrl: '/images/pantai-pandawa.png',
    title: 'Pantai Pandawa, Bali',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 5000000,
    rating: 4.2,
    day: 3,
    night: 1,
    category: 'sea',
    isPopular: false,
  },
  {
    id: 5,
    imageUrl: '/images/pantai-kelingking.png',
    title: 'Pantai Kelingking, Bali',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 4000000,
    rating: 4.1,
    day: 5,
    night: 1,
    category: 'sea',
    isPopular: false,
  },
  {
    id: 6,
    imageUrl: '/images/gn-bromo.png',
    title: 'Gunung Bromo, Jawa Timur',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 2500000,
    rating: 4.8,
    day: 3,
    night: 1,
    category: 'mountain',
    isPopular: true,
  },
  {
    id: 7,
    imageUrl: '/images/gn-semeru.png',
    title: 'Gunung Semeru, Jawa Timur',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 3000000,
    rating: 4.7,
    day: 3,
    night: 1,
    category: 'mountain',
    isPopular: false,
  },
  {
    id: 8,
    imageUrl: '/images/gn-rinjani.png',
    title: 'Gunung Rinjani, Lombok',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 2600000,
    rating: 4.6,
    day: 3,
    night: 1,
    category: 'mountain',
    isPopular: true,
  },
  {
    id: 9,
    imageUrl: '/images/gn-sumbing.png',
    title: 'Gunung Sumbing, Jawa Tengah',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 2500000,
    rating: 4.5,
    day: 3,
    night: 1,
    category: 'mountain',
    isPopular: false,
  },
  {
    id: 10,
    imageUrl: '/images/desa-wae-rebo.png',
    title: 'Desa Wae Rebo, NTT',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 5000000,
    rating: 4.4,
    day: 7,
    night: 2,
    category: 'nature',
    isPopular: false,
  },
  {
    id: 11,
    imageUrl: '/images/bukit-pergasingan.png',
    title: 'Bukit Pergasingan, Lombok',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 5000000,
    rating: 4.3,
    day: 5,
    night: 2,
    category: 'nature',
    isPopular: false,
  },
  {
    id: 12,
    imageUrl: '/images/geopark-ciletuh.png',
    title: 'Geopark Ciletuh, Sukabumi',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 400000,
    rating: 4.2,
    day: 2,
    night: 1,
    category: 'nature',
    isPopular: false,
  },
  {
    id: 13,
    imageUrl: '/images/suspension-brige.png',
    title: 'Suspension Bridge, Sukabumi',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 300000,
    rating: 4.1,
    day: 3,
    night: 1,
    category: 'nature',
    isPopular: false,
  },
  {
    id: 14,
    imageUrl: '/images/curug-ciherang.png',
    title: 'Curug Ciherang, Sukabumi',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 250000,
    rating: 4.8,
    day: 2,
    night: 1,
    category: 'nature',
    isPopular: false,
  },
  {
    id: 15,
    imageUrl: '/images/raja-ampat.png',
    title: 'Raja Ampat, Papua',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 5000000,
    rating: 4.7,
    day: 5,
    night: 2,
    category: 'sea',
    isPolular: true,
  },
  {
    id: 16,
    imageUrl: '/images/danau-toba.png',
    title: 'Danau Toba, Sumatera Utara',
    description: 'Minimum kebarangkatan 10 orang Syarat & Ketentuan Berlaku',
    price: 4000000,
    rating: 4.6,
    day: 3,
    night: 1,
    category: 'nature',
    isPopular: true,
  },
];
